Tags with only anonymized session can be deleted/reassigned
LucasBrazi06/ev-server pull request #1856
Opened 2020-10-22 16:37 UTC by mahdibenromdhane

2020-10-25 19:40 UTC, LucasBrazi06 requested changes

2020-10-25 19:40 UTC, LucasBrazi06 commented on src/storage/mongodb/UserStorage.ts
> +      }]);
Nbr of transaction is related to tags then this filter is not right.
Use the param withUser flag to set this one.

2020-10-27 09:34 UTC, merged

2020-10-27 09:36 UTC, LucasBrazi06 commented
@mahdibenromdhane Could you provide a description for the QA to test (including the auto assignment of the sessions to the new assigned user).
Thanks.

2020-10-27 11:12 UTC, mahdibenromdhane commented
> @mahdibenromdhane Could you provide a description for the QA to test (including the auto assignment of the sessions to the new assigned user).
> Thanks.

Done :)