Tenant request schemas
LucasBrazi06/ev-server pull request #1885
Opened 2020-11-04 16:57 UTC by niklas-la

2020-11-04 16:57 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/LucasBrazi06/ev-server?pullRequest=1885) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/LucasBrazi06/ev-server?pullRequest=1885) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/LucasBrazi06/ev-server?pullRequest=1885) it.</sub>

2020-11-05 12:54 UTC, OliveGerste requested changes

2020-11-05 12:54 UTC, OliveGerste commented on src/assets/server/rest/v1/schemas/tenant/tenant-update-req-super-admin.json
> -    "required": ["id", "name", "email", "subdomain"]
The id is mandatory on the Update request. I think you have to take it back in.

2020-11-05 12:54 UTC, OliveGerste commented on src/assets/server/rest/v1/schemas/tenant/tenant-get-logo-req-super-admin.json
> +    "title": "Tenant Logo",
I would name it consistent. So I would suggest 'TenantLogo Get' in this case.

2020-11-05 12:54 UTC, OliveGerste commented on src/server/rest/v1/validator/TenantValidation.ts
> +    return request;
You return the whole request here. Not the id, which you actually need where you call it. As a result you are not able to edit a tenant anymore.

2020-11-05 12:54 UTC, OliveGerste commented on src/assets/server/rest/v1/schemas/tenant/tenant-get-req-super-admin.json
> +    "title": "Tenant Request",
Same as above. I would name it 'Tenant Get'

2020-11-05 12:56 UTC, OliveGerste commented on src/assets/server/rest/v1/schemas/common/common.json
> +}
Add new lines at the end of the files.

2020-11-07 21:20 UTC, LucasBrazi06 commented
Seems that issues were fixed but still in the **Dev cross-review** pipeline, normal?

2020-11-09 08:26 UTC, OliveGerste commented
> @OliveGerste
> Seems that issues were fixed but still in the **Dev cross-review** pipeline, normal?

@LucasBrazi06 No sorry, I moved it.

2020-11-27 20:01 UTC, merged